# Generated by Django 3.2 on 2021-05-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('contactno', models.IntegerField()),
                ('facility_type', models.CharField(choices=[('OXYGEN', 'Oxygen'), ('COVID BED COVID', 'CovidBed'), ('COVID TESTING', 'CovidTest'), ('DOCTOR ON CALL', 'DoctorCall'), ('AMBULANCE', 'Ambulance'), ('FOOD', 'Food'), ('MEDICINE', 'Medicine')], default='OXYGEN', max_length=15)),
            ],
        ),
    ]
