# Generated by Django 3.2 on 2021-05-01 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInput',
            new_name='UserModel',
        ),
    ]
