# Generated by Django 3.2 on 2021-05-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20210501_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
