# Generated by Django 3.2 on 2021-05-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_usermodel_facility_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='contactno',
            field=models.BigIntegerField(),
        ),
    ]
