# Generated by Django 3.2 on 2021-05-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_alter_usermodel_contactno'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='organization',
            field=models.CharField(default='Kheya', max_length=50),
        ),
    ]
